In [14]:
import cv2
import numpy as np

In [15]:
digits=cv2.imread("/home/sesna/sesna/DL_proj/project/digits1.png",cv2.IMREAD_GRAYSCALE)
test_digits=cv2.imread("/home/sesna/sesna/DL_proj/project/test_digits1.png",cv2.IMREAD_GRAYSCALE)
print(test_digits)
print(len(test_digits))
print(len(digits))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
1000
1000


In [16]:
test_digits = np.vsplit(test_digits,50)  # splitting the image into 50 equal parts of 20 by 20 pixels
print(test_digits)

[array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   9,  33,
          9,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  41, 177, 249,
        178,  29,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,  33, 198, 255, 240,
        255, 107,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   1,  70, 199, 255, 255, 197,
        154, 253,  98,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,  45, 238, 255, 205, 224, 222,
         83, 224, 128,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,  25, 202, 255, 193,  40,  99,  54,
          0, 190, 197,  16,   0,   0,   0],
       [  0,   0,   0,   0,   0,  20, 163, 246, 152,  72,   0, 

In [17]:
test_cells=[]
for d in test_digits:
    d=d.flatten()     # converting to one dim array
    test_cells.append(d)
test_cells=np.array(test_cells,dtype=np.float32)


test_cells


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [18]:
#cv2.imshow('image',test_cells[1])

In [19]:
rows=np.vsplit(digits,50)
cells=[]

for row in rows:
    elem=np.hsplit(row,50)
    for i in elem:
        i=i.flatten()
        cells.append(i)

cells

[array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,  58, 109,  59,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  86,
        226, 255, 223, 155,  73,   3,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,  21, 121, 245, 255, 254, 255, 255, 233,  74,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  48, 193, 255,
        242, 207, 254, 255, 255, 255, 170,   6,   0,   0,   0,   0,   0,
          0,   0,   0,  40, 190, 255, 247, 100,  42, 120, 121, 199, 255,
        192,  14,   0,   0,   0,   0,   0,   0,   0,  19, 168, 255, 243,
        103,   0,   0,   0,   0, 140, 255, 250,  33

In [20]:
cells=np.array(cells,dtype=np.float32)   # converting to same dtype
cells

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [21]:
k=np.arange(10)     # creating a numpy array contaning numbers 0 to 9
cells_labels=np.repeat(k,250)  # creating labels for each cells 
cells_labels

array([0, 0, 0, ..., 9, 9, 9])

In [22]:
knn=cv2.ml.KNearest_create()
knn.train(cells,cv2.ml.ROW_SAMPLE,cells_labels)   # (training data,telling the samples are in  row,lebals corresponding to each sample)


ret,result,neighboursv,dist=knn.findNearest(test_cells,k=20) 

In [23]:
print(result)


[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [3.]
 [3.]
 [4.]
 [3.]
 [3.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [5.]
 [5.]
 [6.]
 [5.]
 [5.]
 [6.]
 [6.]
 [6.]
 [6.]
 [5.]
 [7.]
 [7.]
 [7.]
 [7.]
 [7.]
 [8.]
 [1.]
 [8.]
 [8.]
 [8.]
 [9.]
 [9.]
 [9.]
 [9.]
 [9.]]


In [29]:
import os
from os import listdir
 
# get the path/directory
folder_dir = "/home/sesna/sesna/DL_proj/project/hand.model/num"
for images in os.listdir(folder_dir):
 
    # check if the image ends with png
    if images.endswith(".jpg"):
        image_path = os.path.join(folder_dir, images)
        ja = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
        ja = cv2.resize(ja,(20,20))
       # ja = np.invert(np.array([ja]))

    ret,result,neighboursv,dist=knn.findNearest(ja,k=20) 
    print(result,images)


error: OpenCV(4.7.0) /io/opencv/modules/ml/src/knearest.cpp:313: error: (-215:Assertion failed) test_samples.type() == CV_32F && test_samples.cols == samples.cols in function 'findNearest'
