In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv('/content/drive/MyDrive/datasets/Salary.csv')
df.head()

YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891

In [4]:
df.shape

(35, 2)

In [5]:
x = df['YearsExperience'].values
y = df['Salary'].values

In [6]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
x_train

array([ 4. ,  3.2,  5.1,  3.7, 12.9,  1.1,  2.2,  5.3,  9.6,  2.9,  4. ,
        1.3,  1.5, 12.3,  2. , 11.2,  8.2, 11.5,  3.9,  7.9,  5.9,  9. ,
        3. ,  6.8, 13.5,  3.2,  4.5, 10.3])

In [7]:
x_train = np.vstack((np.ones_like(x_train), x_train)).T
x_train


array([[ 1. ,  4. ],
       [ 1. ,  3.2],
       [ 1. ,  5.1],
       [ 1. ,  3.7],
       [ 1. , 12.9],
       [ 1. ,  1.1],
       [ 1. ,  2.2],
       [ 1. ,  5.3],
       [ 1. ,  9.6],
       [ 1. ,  2.9],
       [ 1. ,  4. ],
       [ 1. ,  1.3],
       [ 1. ,  1.5],
       [ 1. , 12.3],
       [ 1. ,  2. ],
       [ 1. , 11.2],
       [ 1. ,  8.2],
       [ 1. , 11.5],
       [ 1. ,  3.9],
       [ 1. ,  7.9],
       [ 1. ,  5.9],
       [ 1. ,  9. ],
       [ 1. ,  3. ],
       [ 1. ,  6.8],
       [ 1. , 13.5],
       [ 1. ,  3.2],
       [ 1. ,  4.5],
       [ 1. , 10.3]])

In [8]:
x_test = np.vstack((np.ones_like(x_test),x_test)).T
x_test

array([[ 1. ,  9.5],
       [ 1. ,  4.1],
       [ 1. ,  8.7],
       [ 1. ,  7.1],
       [ 1. ,  4.9],
       [ 1. , 10.5],
       [ 1. ,  6. ]])

In [9]:
def linear_regression(X,y,learning_rate,epochs):
  m, n =X.shape          # 28 2
  weights = np.zeros(n)  # [0,0]
  cost_list = []

  for i in range(epochs):
    predictions = np.dot(X, weights)
    error = predictions - y
    gradient = np.dot(X.T,error)/m
    weights -= learning_rate*gradient

    cost = (1/(2*m)) * np.sum(error**2)
    cost_list.append(cost)
  return weights, cost_list


In [10]:
learning_rate = 0.00001
epochs = 20000
weights, cost_list = linear_regression(x_train,y_train,learning_rate,epochs)

y_pred = np.dot(x_test, weights)

mse = np.mean((y_test - y_pred)**2)
rmse = np.sqrt(mse)
mae = np.mean(np.abs(y_test-y_pred))
variance = np.sum((y_test - np.mean(y_test))**2)
r2_score = 1-mse/variance



In [11]:
print("Mean Absolute erroe is ",mse)
print("Root mean squared erroe is ",rmse)
print("Mean absolute error is :",mae)
print("R2_score is: ",r2_score)

Mean Absolute erroe is  104474229.05524495
Root mean squared erroe is  10221.26357429672
Mean absolute error is : 8382.772697249882
R2_score is:  0.9709389969377521


In [12]:
df1 = pd.DataFrame({
    "Actual value":y_test,
    "Predicted value":y_pred,
    "Erroe":y_test-y_pred
})

df1

Actual value  Predicted value         Erroe
0        116969    114022.375227   2946.624773
1         57081     50860.288273   6220.711727
2        109431    104665.029012   4765.970988
3         98273     85950.336581  12322.663419
4         67938     60217.634488   7720.365512
5        121872    125719.057996  -3847.057996
6         93940     73083.985535  20856.014465